// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2017-2023 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "obs-source.hpp"

namespace streamfx::obs {
	namespace tools {
		bool source_find_source(::streamfx::obs::source haystack, ::streamfx::obs::source needle);
	} // namespace tools

	inline void obs_source_deleter(obs_source_t* v)
	{
		obs_source_release(v);
	}

	inline void obs_weak_source_deleter(obs_weak_source_t* v)
	{
		obs_weak_source_release(v);
	}

	inline void obs_scene_deleter(obs_scene_t* v)
	{
		obs_scene_release(v);
	}

	inline void obs_sceneitem_releaser(obs_scene_item* v)
	{
		obs_sceneitem_release(v);
	}

	inline void obs_sceneitem_remover(obs_scene_item* v)
	{
		obs_sceneitem_remove(v);
	}

	inline void obs_data_deleter(obs_data_t* v)
	{
		obs_data_release(v);
	}
} // namespace streamfx::obs
