// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2020-2023 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"

#define S_CODEC_AV1 "Codec.AV1"
#define S_CODEC_AV1_PROFILE "Codec.AV1.Profile"

namespace streamfx::encoder::codec::av1 {
	enum class profile {
		MAIN         = 0,
		HIGH         = 1,
		PROFESSIONAL = 2,
		UNKNOWN      = -1,
	};

	const char* profile_to_string(profile p);
} // namespace streamfx::encoder::codec::av1
