---
name: "File an Feature or Improvement request"
title: "REPLACE ME"
description: "This form is for developers only. Abuse of this form will be met with a permanent interaction ban."
labels: ["enhancement"]
body:
- type: input
  attributes:
    label: "Discussion Thread"
    description: "Please paste the direct link to the discussion thread discussing this feature or improvement."
  validations:
    required: true
