---
name: "File an Improvement Request"
title: "Replace Me Or Have Your Request Closed"
description: "Requests without an accompanying discussion thread will be closed and locked."
labels: ["enhancement"]
body:
- type: input
  attributes:
    label: "Discussion Thread"
    description: "Please paste the direct link to the discussion thread"
  validations:
    required: true
- type: textarea
  attributes:
    label: "Provide a summary of the Improvement"
    description: "This should only include parts that were agreed upon."
  validations:
    required: true
