// AUTOGENERATED COPYRIGHT HEADER START
// Copyright (C) 2020-2023 Michael Fabian 'Xaymar' Dirks <info@xaymar.com>
// AUTOGENERATED COPYRIGHT HEADER END

#pragma once
#include "common.hpp"
#include "ui-common.hpp"

#include "warning-disable.hpp"
#include "ui_about.h"
#include "warning-enable.hpp"

namespace streamfx::ui {
	class about : public QDialog, public Ui::About {
		Q_OBJECT

		public:
		enum class role_type : int32_t {
			NONE,
			CONTRIBUTOR,
			TRANSLATOR,
			SUPPORTER,
		};

		struct entry {
			std::string          name;
			ui::about::role_type role;
			std::string          role_custom;
			std::string          link;
		};

		public:
		about();
		~about();

		public slots:
		; // Not having this breaks some linters.
		void on_ok();
	};
} // namespace streamfx::ui
